[project]
name = "lilviaa-playful-style"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.43.53",
    "fastapi>=0.139.2",
    "passlib[bcrypt]>=1.7.4",
    "pillow>=12.3.0",
    "pydantic-settings>=2.14.2",
    "pydantic[email]>=2.13.4",
    "python-dotenv>=1.2.2",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.32",
    "razorpay>=2.0.1",
    "slowapi>=0.1.10",
    "supabase>=2.31.0",
    "uvicorn>=0.51.0",
]

[dependency-groups]
dev = [
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
]
